[project]
name = "ComfyUI-PreviewMonitor"
description = "Frontend-only node to display ComfyUI previews"
version = "1.0.0" # Custom Node version. Must be semantically versioned.
license = { file = "LICENSE" }
dependencies  = [] # Filled in from requirements.txt

[project.urls]
Repository = "https://github.com/bedovyy/ComfyUI-PreviewMonitor"
"Bug Tracker" = "https://github.com/bedovyy/ComfyUI-PreviewMonitor/issues"

[tool.comfy]
PublisherId = "bedovyy" # TODO (fill in Publisher ID from Comfy Registry Website).
DisplayName = "ComfyUI-PreviewMonitor" # Display name for the Custom Node. Can be changed later.
Icon = "https://raw.githubusercontent.com/bedovyy/ComfyUI-PreviewMonitor/main/assets/logo.png" # SVG, PNG, JPG or GIF (MAX. 800x400px)
